# Generated by Django 4.2.16 on 2026-04-20 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(default='', max_length=255)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='processing', max_length=20)),
                ('token_count', models.IntegerField(default=0)),
                ('result_count', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('MON', 'Money'), ('PCT', 'Percent'), ('DAT', 'Date'), ('TIM', 'Time'), ('CNT', 'Count'), ('FRC', 'Fraction'), ('ORD', 'Ordinal'), ('APX', 'Approximate')], max_length=10)),
                ('raw_value', models.TextField()),
                ('norm_value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('sent_idx', models.IntegerField(default=0)),
                ('start_char', models.IntegerField(default=0)),
                ('end_char', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ner.analysis')),
            ],
            options={
                'ordering': ['sent_idx', 'start_char'],
            },
        ),
    ]
